apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: apm-server
  name: apm-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apm-server
    spec:
      containers:
      - args:
        - apm-server
        - -e
        - -E
        - apm-server.rum.enabled=${RUM_ENABLED}
        - -E
        - apm-server.rum.rate_limit=${RUM_RATE_LIMIT}
        - -E
        - apm-server.rum.allow_origins=${RUM_ALLOW_ORIGINS}
        - -E
        - apm-server.rum.library_pattern=${RUM_LIBRARY_PATTERN}
        - -E
        - apm-server.rum.exclude_from_grouping=${RUM_EXCLUDE_FROM_GROUPING}
        - -E
        - apm-server.rum.source_mapping.cache.expiration=${RUM_SOURCE_MAPPING_CACHE_EXPIRATION}
        - -E
        - apm-server.rum.source_mapping.index_pattern=${RUM_SOURCE_MAPPING_INDEX_PATTERN}
        env:
        - name: RUM_ALLOW_ORIGINS
          value: '[''*'']'
        - name: RUM_ENABLED
          value: "true"
        - name: RUM_EXCLUDE_FROM_GROUPING
          value: '"^/webpack"'
        - name: RUM_LIBRARY_PATTERN
          value: '"node_modules|bower_components|~"'
        - name: RUM_RATE_LIMIT
          value: "10"
        - name: RUM_SOURCE_MAPPING_CACHE_EXPIRATION
          value: 5m
        - name: RUM_SOURCE_MAPPING_INDEX_PATTERN
          value: '"apm-*-sourcemap*"'
        image: docker.elastic.co/apm/apm-server:6.4.3
        name: apm-server
        ports:
        - containerPort: 8200
        resources: {}
      restartPolicy: Always
status: {}
