apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: elasticsearch
    spec:
      terminationGracePeriodSeconds: 300
      initContainers:
        - name: fix-the-volume-premission
          image: busybox
          command:
          - sh
          - -c
          - chown -R 1000:1000 /usr/share/elasticsearch/data
          securityContext:
            privileged: true
          volumeMounts:
            - name: datadir
              mountPath: /usr/share/elasticsearch/data
        - name: increase-the-vm-max-map-count
          # NOTE:
          # To increase the default vm.max_map_count to 262144
          # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
          image: busybox
          command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: increase-the-ulimit
          # To increase the ulimit
          # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
          image: busybox
          command:
          - sh
          - -c
          - ulimit -n 65536
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
          volumeMounts:
            - name: datadir
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              memory: 2Gi
            limits:
              memory: 3Gi
          env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
          livenessProbe:
            exec:
              command:
              - curl
              - -f
              - http://localhost:9200
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "6Gi"
